### ISSUE TITLE
TcpClient will truncate message if it's only a little bit long

### ISSUE THREAD

**Issue by imgen** [chronoxor/NetCoreServer#102]
Hi I am sending a json payload like below
`{"data_type":"device_operations","data":{"device_id":"73b1d505-d586-4f44-bebc-f24aaeaaa861","operations":[{"worker_phone":"12356789","client_phone":"98765321","start_time":"2020-12-10T09:46:55.3217001Z","end_time":"2020-12-10T10:46:55.3217001Z"},{"worker_phone":"12356789","client_phone":"98765321","start_time":"2020-12-10T14:46:55.3217001Z","end_time":"2020-12-10T15:46:55.3217001Z"}]}}`

it's only 388 chars, but when it's sent to the server, it's truncated, causing JSON parse failure. How so?

**Comment by imgen** [comment]
When I use a tool such as `PacketSender`, it can send the bytes just fine. I tried to set a bigger `OptionSendBufferSize` but same thing happened

**Comment by chronoxor** [comment]
For TCP its an upper lever protocol task. Usually you have to send data length 4bytes first, then on the other side read 4 bytes, and start reading until you read all payload and handle it after.

Did you try HTTP/HTTPS server examples? It's ready for json transmitting out of the box.

**Comment by imgen** [comment]
@chronoxor thanks, will take a look at the HTTP server example

**Comment by imgen** [comment]
@chronoxor but is it possible to set a bigger packet size, say 1024 for TcpClient? Currently it is 256 bytes.

**Comment by chronoxor** [comment]
TCP is a streaming protocol. You may send any buffer you like, but it may be chunked into pieces and send in a several TCP packets. If you want a message protocol over TCP you have to write it on your own. As an alternative you may look into - 

HTTP protocol examples:
[HTTP Client](https://github.com/chronoxor/NetCoreServer/blob/master/examples/HttpClient/Program.cs)
[HTTP Server](https://github.com/chronoxor/NetCoreServer/blob/master/examples/HttpServer/Program.cs)

WebSocket protocol examples:
[WebSocket Client](https://github.com/chronoxor/NetCoreServer/blob/master/examples/WssChatClient/Program.cs)|
[WebSocket Server](https://github.com/chronoxor/NetCoreServer/blob/master/examples/WssChatServer/Program.cs)

They are both message based ones.

**Comment by imgen** [comment]
@chronoxor great, thanks. I think my understanding of TCP was quite poor, now it is much clearer to me.
