### ISSUE TITLE
How to read all packets of a message

### ISSUE THREAD

**Issue by imgen** [chronoxor/NetCoreServer#103]
Seems that TCP transmits data in packets, the packet size could vary. How can I read all packets of a message until the end. For example, the TCP client may send a message with size 8192 bytes, it will be sending them in packets of size 256. With simple code, one time will only receive 256 bytes. How can I receive all 8192 bytes?

**Comment by chronoxor** [comment]
For TCP its an upper lever protocol task. Usually you have to send data length 4bytes first, then on the other side read 4 bytes, and start reading until you read all payload and handle it after.

Did you try HTTP/HTTPS server examples? It's ready for json transmitting out of the box.

**Comment by imgen** [comment]
@chronoxor got it, will try
