### ISSUE TITLE
Possible memory leak caused by invalid TcpSessions state

### ISSUE THREAD

**Issue by moustakakisCon** [chronoxor/NetCoreServer#107]
There seems to be a memory leak caused by an invalid state of **TcpSession**:

(memory dump)
![image](https://user-images.githubusercontent.com/672879/103709570-81cb6000-4fbb-11eb-80b3-5cbacf58f530.png)

while the socket seems to be disconnected and disposed, the GameServiceWorker (inherits from **TcpSession**) stays in Connected state and the IsSocketDisposed is False.

this causes the **TcpSessions** to be let in **TcpServer.Sessions** indefinitely causing a memory leak

![image](https://user-images.githubusercontent.com/672879/103710018-9bb97280-4fbc-11eb-80c2-46b37e42dbb3.png)

**Comment by chronoxor** [comment]
TCP session should be unregistered in Disconnect()/Dispose() methods. Can you please check why it is not in your case?
```
bool TcpSession.Disconnect()
{
    ...
  
    // Unregister session
    Server.UnregisterSession(Id);

    return true;
}
```

**Comment by moustakakisCon** [comment]
Sorry, you are right, we were handling the disconnection in a wrong way and instead of 
`TcpSession.Disconnect()` we were calling `TcpSession.Socket.Close()`
