### ISSUE TITLE
Please post symbols to NuGet

### ISSUE THREAD

**Issue by ptr727** [chronoxor/NetCoreServer#11]
Hi, I am unable to step into your code while debugging, using Visual studio 2019 Preview and DotNet Core 3.0 Console project.

Can you please post debug symbols with your package to the NuGet repository?
See: https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg

**Comment by chronoxor** [comment]
```
Pushing NetCoreServer.1.6.0.nupkg to 'https://www.nuget.org/api/v2/package'...
  PUT https://www.nuget.org/api/v2/package/
  Created https://www.nuget.org/api/v2/package/ 1219ms
Your package was pushed.
Pushing NetCoreServer.1.6.0.snupkg to 'https://www.nuget.org/api/v2/symbolpackage'...
  PUT https://www.nuget.org/api/v2/symbolpackage/
  Created https://www.nuget.org/api/v2/symbolpackage/ 580ms
Your package was pushed.
```

**Comment by ptr727** [comment]
Hi, thank you, I see the new v1.6 package, but I do not see symbols or sourcelink information?

See:
https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink
https://github.com/dotnet/sourcelink
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/releases

The NuGetPackageExplorer only shows the DLL?
