### ISSUE TITLE
http response add header

### ISSUE THREAD

**Issue by wingyukyuk** [chronoxor/NetCoreServer#113]
I am sorry about to asking this question,
May i know can/ how to update/ add the http response Header and Cookie,
I try HttpResponse.SetHeader and HttpResponse.SetCookie which is not working.
i can't found any example and document relate to this.

`        protected override void OnReceivedRequest(HttpRequest request)
        {
                SendResponseAsync(Response.MakeGetResponse("OK").SetHeader("Access-Control-Allow-Origin", "*"));
        }
`

Many Thanks

**Comment by chronoxor** [comment]
You can experiment with https://github.com/chronoxor/NetCoreServer/blob/master/examples/HttpsClient/Program.cs in a following way:
```
                else if (commands[0].ToUpper() == "GET")
                {
                    var request = client.Request;
                    request.Clear();
                    request.SetBegin("GET", commands[1]);
                    request.SetHeader("Host", client.Address);
                    request.SetHeader("Cookie", "MySession=9CB9E7C3-E52E-46F1-BD94-D7964CCF885A");
                    request.SetBody();

                    var response = client.SendRequest(request).Result;
                    Console.WriteLine(response);
                }
```

**Comment by wingyukyuk** [comment]
I succeed by using the following code, thanks for your help!

`            var r = Response.Clear();
            r.SetBegin(200);
            r.SetHeader("Content-Type", "application/json; charset=UTF-8");
            r.SetHeader("Access-Control-Allow-Origin", "*");
            r.SetHeader("Access-Control-Allow-Methods", "GET, PUT, POST, DELETE, OPTIONS");
            r.SetCookie("MySession", "9CB9E7C3-E52E-46F1-BD94-D7964CCF885A",300,"","",false,false);
            r.SetBody("{}");
            SendResponseAsync(r);
`
