### ISSUE TITLE
Socket.RemoteEndPoint exception in OnWsDisconnected

### ISSUE THREAD

**Issue by Dmitriy147** [chronoxor/NetCoreServer#116]
In my websocket chat server I try to use Socket.RemoteEndPoint to show the IP-adress of client, but ,unfortunately, in case "OnWsDisconnected" in attemp to show IP of disconnected client it is an exception like:
System.ObjectDisposedException: "Cannot access a disposed object.
ObjectDisposed_ObjectName_Name".

With showing client ID in this situation has no problems!
Is it any way to show IP of disconnected client without making array of all clients IP?

**Comment by chronoxor** [comment]
Fixed in 5.0.8 please try!

**Comment by Dmitriy147** [comment]
No effect on 5.0.8.. From Google Chrome connect by websocket throw chat/index.html - connect by websockets - than disconnect - exception appeared..

**Comment by chronoxor** [comment]
It's the behavior of .net Socket it will dispose RemoteEndPoint property on Socket.Close() call.  OnWsDisconnected() is called after the socket is closed.

What do you think of introducing OnWsDisconnecting() callback with valid connected socket in it?

**Comment by chronoxor** [comment]
The flow can be the following:
```
OnWsDisconnecting();
Socket.Close();
OnWsDisconnected();
Socket.Dispose();
```

**Comment by Dmitriy147** [comment]
would be nice!

**Comment by chronoxor** [comment]
In our logs we store this information in a following way:
```
2021-02-18T00:55:53.926Z [0x000023B4] INFO  endpoints - TCP config session with Id '0ccb739f-7184-11eb-b134-240a646eaeae' connected to remote address '127.0.0.1' and port 58148
....
2021-02-18T00:55:56.029Z [0x000023B4] INFO  endpoints - TCP config session with Id '0ccb739f-7184-11eb-b134-240a646eaeae' disconnected
```

**Comment by chronoxor** [comment]
New handlers implemented.
