### ISSUE TITLE
AddStaticContent how to refresh content

### ISSUE THREAD

**Issue by Dmitriy147** [chronoxor/NetCoreServer#119]
In my WsServer I has two (is it works correctly) folders throw AddStaticContent.. The first has index.html for connections to my server, the second - simple folder for visit some html pages in it throw my WsServer by Opera or other browsers.
The problem is if once I start server, the html pages in my folders seems to fix in cash - any changes in them I could not see in my browsers throw WsServer. If I open any changed pages directly  - all changes are visible!
Sorry, may be my settings of wsServer needs to change...(v.5.0.13)

**Comment by chronoxor** [comment]
In `void AddStaticContent(string path, string prefix = "/", TimeSpan? timeout = null)` you can provide a desired timeout of TimeSpan type. By default content will be valid for one hour. For developing purpose you may put 1 second timeout to detect your changes immediately.

Filesystem watching it not currently implemented.

**Comment by Dmitriy147** [comment]
Try to put TimeSpan(0,0,1)  - no result..

**Comment by chronoxor** [comment]
I'll look into it. Fix will be available soon.

**Comment by chronoxor** [comment]
New version - 5.0.14: HTTP servers can handle filesystem changes on a fly. Please check it on your side.

**Comment by Dmitriy147** [comment]
Ok! Pages refresh works stable. Thanks!

**Comment by Dmitriy147** [comment]
Am i correctly understood?:  the wsservers can handle filesystem changes on a fly. Is it now able not to refresh the page manualy  - the page on the client's screen can be reload on a fly from wsserver?
