### ISSUE TITLE
Validate?

### ISSUE THREAD

**Issue by tfevzi** [chronoxor/NetCoreServer#123]
Hi! 
How can i validate certificate for both server and client connection?

**Comment by chronoxor** [comment]
On a server side you should prepare SslContext.Certificate and set `SslContext.ClientCertificateRequired = true`
```
// Begin the SSL handshake
_sslStream.BeginAuthenticateAsServer(Server.Context.Certificate, Server.Context.ClientCertificateRequired, Server.Context.Protocols, false, ProcessHandshake, _sslStreamId);
```

On a client side you should prepare client certificate in `X509Certificate SslContext.Certificate` or more than one certificates in `X509Certificate2Collection SslContext.Certificates`
```
// SSL handshake
_sslStream.AuthenticateAsClient(Address, Context.Certificates ?? new X509CertificateCollection(new[] { Context.Certificate }), Context.Protocols, true);
```

**Comment by chronoxor** [comment]
For more about certificate validation you can read here:
https://dotnetcodr.com/2016/01/21/using-client-certificates-in-net-part-4-working-with-client-certificates-in-code/

**Comment by tfevzi** [comment]
Thanks for the quick solution.
