### ISSUE TITLE
Data Lost

### ISSUE THREAD

**Issue by tfevzi** [chronoxor/NetCoreServer#125]
Hi! 
First of all thank you for supports. i'm using ssl server and clients. my clients sends me random data which is size under 16355 byte. and its working but when is data bigger than 16355 server reads only 16355 byte of data. (i increased buffer size)
what should I do?

**Comment by tfevzi** [comment]
I found what I was missing and fixed it. Thanks :)

**Comment by TailyFair** [comment]
Out of curiosity what you were missing?

**Comment by tfevzi** [comment]
@TailyFair 
Hi,
In the OnReceived event, I checked "incoming byte size" that all bytes are coming, and I combined all data until the value is 0 during the current session. and I triggered a different "event" and called a different class in this "event" that also handles the incoming data.

If I do not do this, the json data that comes in fragmented form is missing. error occurs in this case.

(My English is poor, I hope I explained it right)
