### ISSUE TITLE
Can't install nuget packet with .netcoreapp

### ISSUE THREAD

**Issue by shersh** [chronoxor/NetCoreServer#126]
Installing NetCoreServer 5.0.15.
NU1202: Package NetCoreServer 5.0.15 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1). Package NetCoreServer 5.0.15 supports: net5.0 (.NETCoreApp,Version=v5.0)

**Comment by dj-curls** [comment]
NetCoreServer v5 and above is for .NET 5, you'll probably have to manually specify v3.0.22 in nuget
