### ISSUE TITLE
Issue using in .NetCore 2.1

### ISSUE THREAD

**Issue by ReeceKetley** [chronoxor/NetCoreServer#13]
Im not sure if im being silly but i can't use this is in .netcore 2.2/2.1/2.0 as the nuget package seems to target netstandard

**Comment by BlowaXD** [comment]
If you are trying to use NetCoreServer 1.6.0 (latest package available on nuget) it's normal, it's using .NET standard 2.1 which is supported by .NET Core 3.

**Comment by chronoxor** [comment]
.NET Core 2.0: Install-Package NetCoreServer -Version 2.0.0
.NET Core 3.0: Install-Package NetCoreServer -Version 3.0.0
