### ISSUE TITLE
WSClient don't support continuation frames(opcode 0)

### ISSUE THREAD

**Issue by Vjacheslaw** [chronoxor/NetCoreServer#133]
I use on server WebSocketSharp(but this dont matter): he sent fragment pakage, where size pakage is 1016.
WsClient recive only first fragment.

![image](https://user-images.githubusercontent.com/43916814/119515659-b9765100-bd7e-11eb-8caa-4283212e4d66.png)
OpCode is 0(continuation frame).
https://datatracker.ietf.org/doc/html/rfc6455#section-5.4

**Comment by chronoxor** [comment]
Yes, now I understand the issue. We need WsReceiving flag to collect all fragments. Soon the fix will be available. I'll be appreciated if you could check it on your side!

**Comment by chronoxor** [comment]
Can you please check why WsReceiveBuffer flushes/clear after the first frame is received? According to design "lo" should be append to WsReceiveBuffer, which should already contains opcode in WsReceiveBuffer[0] and also "Hel" part.

**Comment by chronoxor** [comment]
Please check the fix

**Comment by chronoxor** [comment]
Please check the fix

**Comment by Vjacheslaw** [comment]
Yes it works
