### ISSUE TITLE
Update readme for HttpResponse.MakeErrorResponse format

### ISSUE THREAD

**Issue by derekantrican** [chronoxor/NetCoreServer#134]
The Readme seems to indicate this is the way to send a 404 error response from HttpSession:

```
SendResponseAsync(Response.MakeErrorResponse("Required cache value was not found for the key: " + key, 404));
```

But when I try that locally, I do not have an integer parameter option for `HttpResponse,.MakeErrorResponse`. I only have the following:

```
public HttpResponse MakeErrorResponse(string content = "", string contentType = "text/plain; charset=UTF-8");
public HttpResponse MakeErrorResponse(int status, string content = "", string contentType = "text/plain; charset=UTF-8");
```

Am I missing something?

**Comment by derekantrican** [comment]
Ah, upon closer inspection I *do* have that option:

```
SendResponseAsync(Response.MakeErrorResponse(404, ""));
```

Still, the Readme needs to be updated

**Comment by chronoxor** [comment]
Fixed
