### ISSUE TITLE
SendBuffer ignores array constraints

### ISSUE THREAD

**Issue by Vjacheslaw** [chronoxor/NetCoreServer#137]
Array have constraint. In x64 is 2,147,483,647 elements(https://stackoverflow.com/questions/2338778/what-is-the-maximum-length-of-an-array-in-net-on-64-bit-windows).

Accordingly, if you send a lot of messages in a short period of time, the Buffer.Append() will try to increase the buffer size by an impossible one.

In example(TcpEchoClient):
Set messages to value 2100000000;
![image](https://user-images.githubusercontent.com/43916814/120089239-12d4dc00-c101-11eb-8a7d-2fb48432ebdb.png)

Catch the error:
![image](https://user-images.githubusercontent.com/43916814/120089269-40218a00-c101-11eb-9df6-3b4d54e6be14.png)

**Comment by chronoxor** [comment]
It is known behavior - slow client issue. Your server & clients should be balanced in producing and consuming data. You should control send & receive buffers with BytesPending/BytesSending properties. If they exceed for example 10mb for session you should manually disconnect slow client!

**Comment by Vjacheslaw** [comment]
Let's admit. The next question is: "Where does the buffer size change?" The buffer (send / receive) only grows. 

As an example: The usual client package to send is 32-bit. But sometimes the packet is bigger - as far as I understand it will increase the server side buffer forever.

**Comment by Vjacheslaw** [comment]
Or "disconnect slow client" is only way make buffer small again?

**Comment by chronoxor** [comment]
If you look into TryReceive() method you'll find out:
```
                    // Async receive with the receive handler
                    _receiving = true;
                    _receiveEventArg.SetBuffer(_receiveBuffer.Data, 0, (int)_receiveBuffer.Capacity);
                    if (!Socket.ReceiveAsync(_receiveEventArg))
                        process = ProcessReceive(_receiveEventArg);
```
that each new iteration we start receive buffer from 0 offset with _receiveBuffer.Capacity. After socket get new data it will set buffer size. Which we handle in ProcessReceive and increase buffer capacity in case it's big:
```
                // If the receive buffer is full increase its size
                if (_receiveBuffer.Capacity == size)
                    _receiveBuffer.Reserve(2 * size);
```
The size of receive buffer can be controled in OnReceived() handle and the client or server can be disconnected if the buffer grows too big. 

The same logic with send buffers. They are cleared in ProcessSend:
```
                // Successfully send the whole flush buffer
                if (_sendBufferFlushOffset == _sendBufferFlush.Size)
                {
                    // Clear the flush buffer
                    _sendBufferFlush.Clear();
                    _sendBufferFlushOffset = 0;
                }
```
and can be checked for big size in OnSent() handler in your code.

That's how we do it in our servers.

**Comment by chronoxor** [comment]
If you see somewhere that your buffers are too big just call Disconnect() method. And kick off bad-slow client!

**Comment by chronoxor** [comment]
Please see OptionReceiveBufferLimit & OptionSendBufferLimit properties for clients and sessions in version 5.1.0
