### ISSUE TITLE
What is this Wizardry?

### ISSUE THREAD

**Issue by volundmush** [chronoxor/NetCoreServer#14]
This isn't actually an issue with the code, and more with my difficulty in figuring out what's happening under the hood.

I'm designing an application that needs to run a telnet server - gonna be running a MUD game, hopefully! And I'd like to use this for the networking. So far so good, the server is up and echoing some text back as it's sent...

But I don't understand how this library works. What mechanisms are being used under the hood to achieve responsiveness? Is this running in its own thread for instance? Thread-per-connection? I've seen some usage of Events but I also saw a Thread.Yield() and lots of using System.Threading but I'm not seeing Threads actually CREATED anywhere either...

Since I need to design my main loop and everything related, I kinda need to know how this thing fits into the equation.

I'm a little new to C#, so...

**Comment by jhmckimm** [comment]
This uses async sockets. Any events triggered will be executed asynchronously, so you'll need to handle this in your application.

**Comment by vgrudenic** [comment]
@volundmush With async tasks, code either gets executed on a free `ThreadPool` thread, or on the thread captured by the context (in case you are doing UI stuff and need to dispatch the results back on the one-and-only UI thread). I/O work also runs on dedicated OS threads, which is supported throughout the OS with [IOCP ](https://docs.microsoft.com/en-us/windows/win32/fileio/i-o-completion-ports). The main idea is to keep the number of threads low (e.g. tied to the number of cores) and dispatch tasks around them without additional allocations and without too much chattiness between cores.

[This article](https://blog.stephencleary.com/2013/11/there-is-no-thread.html) sums it up for .NET tasks, although it goes all the way to the CPU interrupts to explain how the whole process works.

**Comment by volundmush** [comment]
Thanks. Did some research after getting this info. Things make far more sense now. It never occurred to me that C# worked like this.
