### ISSUE TITLE
add mimeTypes to HttpResponse

### ISSUE THREAD

**Issue by bufferUnderrun** [chronoxor/NetCoreServer#160]
Hi,

I need to add some mimeTypes to HttpResponse (iex: .vue).

What's the best way achieving this ?
I can propose a PR with your consent.

Thanks

**Comment by chronoxor** [comment]
Yes, please show which new extensions/mimes you need via proposing a PR

**Comment by bufferUnderrun** [comment]
there is a PR but using a public method in HttpResponse would be better for proper user customization.

**Comment by chronoxor** [comment]
Merged, thanks! For user custom mime please use HttpResponse.SetHeader("Content-Type", "custom_mime") method.

**Comment by bufferUnderrun** [comment]
> Merged, thanks! For user custom mime please use HttpResponse.SetHeader("Content-Type", "custom_mime") method.

Perfect !!
