### ISSUE TITLE
Getting IP address of newly connected client

### ISSUE THREAD

**Issue by furkangkhsn** [chronoxor/NetCoreServer#208]
If i try to access this.Socket from the constructor of TcpSession, it returns null. How can i access to client's ip address from constructor?

**Comment by chronoxor** [comment]
It is designed that this.Socket is initialized in `TcpSession.Connect(Socket socket)`. In your code you can override `OnConnecting()` or `OnConnected()` and access initialized and valid this.Socket property.

**Comment by furkangkhsn** [comment]
Thank you.
