### ISSUE TITLE
Net.Framework 4.7.2 compatibility?

### ISSUE THREAD

**Issue by RabbitProductions** [chronoxor/NetCoreServer#212]
Hello,
I am developing a project on Net.Framework 4.7.2. 
I was wondering if support is planned to be added to this version. It would be a great help!
Thanks.

**Comment by chronoxor** [comment]
Please see [NetFramework-4.6 branch](https://github.com/chronoxor/NetCoreServer/tree/NetFramework-4.6)

**Comment by RabbitProductions** [comment]
Thank you! Changing the TargetFramework works now.
