### ISSUE TITLE
Browser connections fail with "A server must not mask any frames that it sends to the client"

### ISSUE THREAD

**Issue by paoloambrosio** [chronoxor/NetCoreServer#213]
Since upgrading from 6.2.0 to 6.4.0, WebSockets connections from the Web browser (Chrome 104.0.5112.81) stopped working. The error is `A server must not mask any frames that it sends to the client.`

It can be reproduced in the WsChatServer example.

6.2.0:
![image](https://user-images.githubusercontent.com/188185/184415788-bd0a2988-dbc4-4094-9e39-94c9f70d1920.png)

6.4.0:
![image](https://user-images.githubusercontent.com/188185/184415932-050a3eae-a091-451a-96a9-0b178ad62934.png)

**Comment by chronoxor** [comment]
Will look...

**Comment by chronoxor** [comment]
Fixed. Please check version 6.5.0

**Comment by paoloambrosio** [comment]
Upgrading to 6.5.0 fixed the issue both in the example and my software. Thanks!
