### ISSUE TITLE
Do I have to use the websocket client in this library?

### ISSUE THREAD

**Issue by KieranDevvs** [chronoxor/NetCoreServer#216]
I've got a `NetCoreServer.WsServer` running and i'm trying to connect with `System.Net.WebSockets.ClientWebSocket` via blazor WASM. I can connect fine but as soon as I send data, I get:
```
WebSocket connection to 'ws://localhost:25566/' failed: Invalid frame header
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: The WebSocket is in an invalid state ('Closed') for this operation. Valid states are: 'Open, CloseSent'
System.Net.WebSockets.WebSocketException (0x80004005): The WebSocket is in an invalid state ('Closed') for this operation. Valid states are: 'Open, CloseSent'
   at System.Net.WebSockets.BrowserWebSocket.ReceiveAsync(ArraySegment`1 buffer, CancellationToken cancellationToken)
```

Seeing as I don't control the frame header or the WS handshake, I assume this is something to do with client / server compatibility?

Just read the `WsClient` documentation and it would seem that in the example, it explicitly sets the header info:
```cs
public override void OnWsConnecting(HttpRequest request)
{
    request.SetBegin("GET", "/");
    request.SetHeader("Host", "localhost");
    request.SetHeader("Origin", "http://localhost");
    request.SetHeader("Upgrade", "websocket");
    request.SetHeader("Connection", "Upgrade");
    request.SetHeader("Sec-WebSocket-Key", Convert.ToBase64String(WsNonce));
    request.SetHeader("Sec-WebSocket-Protocol", "chat, superchat");
    request.SetHeader("Sec-WebSocket-Version", "13");
    request.SetBody();
}
```

Shouldn't the server accept any client that meets the WS standard? 

Edit: I've just tried to use the `WsClient` in Blazor WASM but the sandbox doesn't allow usage of `System.Net.Socket`, which means without being able to get `System.Net.WebSockets.ClientWebSocket` working, I cant use this library for websocket connections.

**Comment by chronoxor** [comment]
Yes, WebSocket server from NetCoreServer should work with any WS client from other libs and browsers as well. Can you try if https://github.com/chronoxor/NetCoreServer#example-websocket-chat-server works fine in your browser first?

**Comment by KieranDevvs** [comment]
> Yes, WebSocket server from NetCoreServer should work with any WS client from other libs and browsers as well. Can you try if https://github.com/chronoxor/NetCoreServer#example-websocket-chat-server works fine in your browser first?

You are correct, it does work with other clients. The mistake I had was, I used `SendAsync` with the overload for a `byte[]` rather than `SendBinaryAsync`. I assume the difference is that `Send/SendAsync` just sends the raw data without framing it, whereas `SendBinary/SendBinaryAsync` does the frame headers for you?

**Comment by chronoxor** [comment]
Yes, this is the issue - for WebSockets you should use only SendText/SendBinary/SendClose/SendPing/SendPong (sync or async) methods. Send/SendAsync - are methods from lower TCP/SSL layer, which are send raw bytes, but not prepared WebSockets frame message.

**Comment by KieranDevvs** [comment]
> Yes, this is the issue - for WebSockets you should use only SendText/SendBinary/SendClose/SendPing/SendPong (sync or async) methods. Send/SendAsync - are methods from lower TCP/SSL layer, which are send raw bytes, but not prepared WebSockets frame message.

Thanks for the help.
