### ISSUE TITLE
Checking client certificate (public key) for authentication purposes

### ISSUE THREAD

**Issue by RonnieJorgensen** [chronoxor/NetCoreServer#228]
I'm using WssServer and WssClient, but I can't find any way to, from the server, see the public key part of the client's certificate. I want to do that in order to verify who the client is.
Is there any way to do this out-of-the-box?

**Comment by chronoxor** [comment]
Please look into [SslContext.cs](https://github.com/chronoxor/NetCoreServer/blob/master/source/NetCoreServer/SslContext.cs). There is a constructor with [RemoteCertificateValidationCallback](https://learn.microsoft.com/en-us/dotnet/api/system.net.security.remotecertificatevalidationcallback?view=net-6.0) argument that should be used as a custom client certificate validation callback:

```
var context = new SslContext(SslProtocols.Tls12, new X509Certificate2("server.pfx", "qwerty"), (sender, certificate, chain, sslPolicyErrors) => true);
```

**Comment by RonnieJorgensen** [comment]
@chronoxor thanks, that was what I was looking for. I had to set ClientCertificateRequired to true on the context, on server-side, in order to get the client certificate properly, but it seems to be per design.
