### ISSUE TITLE
Extended payload length bug.

### ISSUE THREAD

**Issue by pjngit** [chronoxor/NetCoreServer#229]
Great library. Fun bug in source/NetCoreServer/WebSocket.cs: :o)

PrepareSendFrame(): size should be long (It doesn't work correctly with size > 0xFFFF)

public void PrepareSendFrame(byte opcode, bool mask, ReadOnlySpan<byte> buffer, int status = 0)
        {
            int size = buffer.Length; **//todo: long size**
...
            {
                WsSendBuffer.Append((byte)(127 | (mask ? 0x80 : 0)));
                for (int i = 7; i >= 0; i--)
                    WsSendBuffer.Append((byte)((size >> (8 * i)) & 0xFF)); **//NOTE: (int)123456 >> 48 = 1 in C#**
            }

**Its strange but true:**
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/bitwise-and-shift-operators#shift-count-of-the-shift-operators

For the x << count, x >> count, and x >>> count expressions, the actual shift count depends on the type of x as follows:

**If the type of x is int or uint, the shift count is defined by the low-order five bits of the right-hand operand. That is, the shift count is computed from count & 0x1F (or count & 0b_1_1111).**

If the type of x is long or ulong, the shift count is defined by the low-order six bits of the right-hand operand. That is, the shift count is computed from count & 0x3F (or count & 0b_11_1111).

**Comment by chronoxor** [comment]
Thanks for reporting! Please check the fix in 6.7.0.0

**Comment by pjngit** [comment]
Thank you for the quick fix. Close status codes are a really nice addition.

I would consider making WebSocket.PrepareSendFrame parameters "mask" and "status" members of WebSocket. 

Mask is constant for a given endpoint.
Status could be renamed to CloseStatusCode and only be set on close.

2 less parameters to pass for every frame -> better performance.

Some double code could also be avoided:
```
        public void PrepareSendFrame(byte fin_rsv_opcode, ReadOnlySpan<byte> buffer)
        {
            bool close = ((fin_rsv_opcode & WS_CLOSE) == WS_CLOSE) && (buffer.Length > 0);
            long size = close ? buffer.Length + 2 : buffer.Length;
...
            // Append WebSocket close status
            if (close)
            {
                index += 2;
                WsSendBuffer.Append((byte)((CloseStatus >> 8) & 0xFF));
                WsSendBuffer.Append((byte)(CloseStatus & 0xFF));
            }
...

```

Also consider adding a comment about why "(buffer.Length > 0)" is only related to close.
/Cheers.

**Comment by pjngit** [comment]
👍

**Comment by JocPelletier** [comment]
Not sure if it's related to this issue, but with version 6.2 everything works fine for me, upgraded to 6.7 and I'm now having:

```
Unhandled Exception - Message: Index was outside the bounds of the array.  Source: NetCoreServer  InnerMessage:
Stacktrace:    at NetCoreServer.WebSocket.PrepareSendFrame(Byte opcode, Boolean mask, ReadOnlySpan`1 buffer, Int32 status)->   at NetCoreServer.WsSession.SendPongAsync(ReadOnlySpan`1 buffer)->   at NetCoreServer.WsSession.SendPongAsync(Byte[] buffer, Int64 offset, Int64 size)->   at NetCoreServer.WsSession.OnWsPing(Byte[] buffer, Int64 offset, Int64 size)->   at NetCoreServer.WebSocket.PrepareReceiveFrame(Byte[] buffer, Int64 offset, Int64 size)->   at NetCoreServer.TcpSession.ProcessReceive(SocketAsyncEventArgs e)->   at NetCoreServer.TcpSession.OnAsyncCompleted(Object sender, SocketAsyncEventArgs e)->   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)->--- End of stack trace from previous location ---->   at System.Net.Sockets.SocketAsyncEngine.System.Threading.IThreadPoolWorkItem.Execute()->   at System.Threading.ThreadPoolWorkQueue.Dispatch()->   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()->   at System.Threading.Thread.StartCallback()
```

**Comment by detunized** [comment]
I experience the same. I believe it's a bug. I opened the issue: https://github.com/chronoxor/NetCoreServer/issues/253

> Not sure if it's related to this issue, but with version 6.2 everything works fine for me, upgraded to 6.7 and I'm now having:
> 
> ```
> Unhandled Exception - Message: Index was outside the bounds of the array.  Source: NetCoreServer  InnerMessage:
> Stacktrace:    at NetCoreServer.WebSocket.PrepareSendFrame(Byte opcode, Boolean mask, ReadOnlySpan`1 buffer, Int32 status)
>    at NetCoreServer.WsSession.SendPongAsync(ReadOnlySpan`1 buffer)
>    at NetCoreServer.WsSession.SendPongAsync(Byte[] buffer, Int64 offset, Int64 size)
>    at NetCoreServer.WsSession.OnWsPing(Byte[] buffer, Int64 offset, Int64 size)
>    at NetCoreServer.WebSocket.PrepareReceiveFrame(Byte[] buffer, Int64 offset, Int64 size)
>    at NetCoreServer.TcpSession.ProcessReceive(SocketAsyncEventArgs e)
>    at NetCoreServer.TcpSession.OnAsyncCompleted(Object sender, SocketAsyncEventArgs e)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location ---
>    at System.Net.Sockets.SocketAsyncEngine.System.Threading.IThreadPoolWorkItem.Execute()
>    at System.Threading.ThreadPoolWorkQueue.Dispatch()
>    at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
>    at System.Threading.Thread.StartCallback()
> ```
