### ISSUE TITLE
When is the OnEmpty method called? Could use a short comment.

### ISSUE THREAD

**Issue by Mufanza** [chronoxor/NetCoreServer#232]
First of all: thanks a lot for the excellent library man! It's a pleasure to work with really.

What exactly triggers the OnEmpty method? All of the other events are pretty self-explanatory, but I can't figure out what the use-case of this one is. A short summary could really come-in handy :)

**Comment by chronoxor** [comment]
```
Notification is called when the send buffer is empty and ready for a new data to send.
This handler could be used to send another buffer to the client.
```

This notification indicates that client/session has no more data to send and its send buffer is empty. Typically this may trigger some file reader or consumer to generate some new data to send.

`OnEmpty()` is called after `OnConnected()` handler if nothing was send after connection is established and from `TrySend()` method when send buffer becomes empty.

**Comment by Mufanza** [comment]
Ah, I'm using the NetCore-3.0 branch so perhaps that's why I missed this docummentation.
Anyway, thanks! This explains it.
