### ISSUE TITLE
Update SSL context without new instance

### ISSUE THREAD

**Issue by 80O** [chronoxor/NetCoreServer#237]
Is it possible to update the SSL Context once the server has been started? As I use Lets Encrypt for its certificates, they are only valid for 90 days. As the SSL context is passed in the constructor, its not possible anymore to change it. And if my certificates expire, a full restart of my application is required instead.

**Comment by chronoxor** [comment]
Yes, you can update Server.Context public properties and all new sessions will use a new certificate and validation cert callback.
