### ISSUE TITLE
What value should pass when call Close(int status) method?

### ISSUE THREAD

**Issue by CwjXFH** [chronoxor/NetCoreServer#240]
When I want to close a WsSession, I will call Close(int status), but what status value should I pass? In the README file, the status's value is 1000, why? Can I give another value?

![image](https://user-images.githubusercontent.com/11468733/209911193-68b08f75-a2ac-4eda-86fa-39c626edebe2.png)

**Comment by chronoxor** [comment]
```
1000 CLOSE_NORMAL

1000 indicates a normal closure, meaning that the purpose for which the connection was established has been fulfilled.
```
https://kapeli.com/cheat_sheets/WebSocket_Status_Codes.docset/Contents/Resources/Documents/index
