### ISSUE TITLE
[Question] Upload Large Files Using TCP

### ISSUE THREAD

**Issue by D3c0ded** [chronoxor/NetCoreServer#241]
Hi, first of all thanks for this great project, This is the first time I'm gonna use this library, can I use this library to upload large files (~250MB) via TCP? Should I do something extra?
Regards.

**Comment by chronoxor** [comment]
The right design is to send big file as a sequence of small chunks (near to TCP window size of 64kb) on a client. On a server side just get the first chunk, create a file and then append all other chunks till the last one. As NetCoreServer provides raw TCP streaming, you have to implement kind of your own file upload protocol with FileUploadBegin, FileUploadChunk, FileUploadEnd requests.

**Comment by D3c0ded** [comment]
Thanks.

**Comment by donnyv** [comment]
Does anyone have any examples for chunking files and putting them back together? Also adding those new events? Really wanted to use this library since I couldn't find any up to date .net core tcp file transfer libraries. They all seemed to have been abandoned.
