### ISSUE TITLE
How to Choose an Ethernet Adapter

### ISSUE THREAD

**Issue by GGorany** [chronoxor/NetCoreServer#266]
I envision a test simulation like the one below.

1. Multiple USBtoEthernet Adapters.
2. One Client for each USBtoEthernet Adapter.
3. Client is TcpClient using netcoreServer.

So, I want to select USBtoEthernet Adapter through netcoreServer.

I mean I'm asking how to set LocalEndPont.

I would really appreciate it if you could let me know if there is any way.

**Comment by akanwischer** [comment]
Extend the tcp client, override `CreateSocket` and bind your socket to your interface via `Socket.Bind`.  Alternatively, use a search engine of your choice.

**Comment by GGorany** [comment]
> Extend the tcp client, override `CreateSocket` and bind your socket to your interface via `Socket.Bind`. Alternatively, use a search engine of your choice.


I wanted to solve the problem without modifying the TCP Client library.
Thank you so much.

**Comment by akanwischer** [comment]
But `CreateSocket` has `protected` as access modifier for a reason ;)
