### ISSUE TITLE
Make available linger state

### ISSUE THREAD

**Issue by Ilkhom-S** [chronoxor/NetCoreServer#27]
Can you make available for setting linger state options. Also, Reuse port is comment out in code.

**Comment by chronoxor** [comment]
SocketOptionName.ReuseAddress will set SO_REUSEPORT in Linux according to the latest corefx sources: https://github.com/dotnet/corefx/blob/bc115700c3ece60acd6b8dbe4b0bdb8f6f80c756/src/Native/Unix/System.Native/pal_networking.c

**Comment by Ilkhom-S** [comment]
Is this same behavior for windows also ?

**Comment by chronoxor** [comment]
![image](https://user-images.githubusercontent.com/4397805/69740731-e8d8dd00-114a-11ea-83a7-0bf4d4c17e86.png)

**Comment by chronoxor** [comment]
Yes just set `OptionReuseAddress = true`

**Comment by Ilkhom-S** [comment]
Thanks, what about linger state ?

**Comment by chronoxor** [comment]
Just add OptionExclusiveAddressUse option for some exotic cases:
```
        /// <summary>
        /// Option: enables a socket to be bound for exclusive access
        /// </summary>
        /// <remarks>
        /// This option will enable/disable SO_EXCLUSIVEADDRUSE if the OS support this feature
        /// </remarks>
        public bool OptionExclusiveAddressUse { get; set; }
```

linger state will be available in a moments

**Comment by Ilkhom-S** [comment]
Thanks,

**Comment by chronoxor** [comment]
```
        /// <summary>
        /// Option: linger state
        /// </summary>
        public LingerOption OptionLingerState
        {
            get => Socket.LingerState;
            set => Socket.LingerState = value;
        }
```
