### ISSUE TITLE
Why the cache is not updated?

### ISSUE THREAD

**Issue by vvyoko** [chronoxor/NetCoreServer#276]
I use the http server and set static
`server.AddStaticContent(www);`
`FileSystemWatcher`  event trigger fine

But cache not update
After test I find problem in `FileCache.Find`
Add trigger in file changed
Find trigger in request

`s0` `s1` `s2` is the new value
but `s3` Call in Add() is the new value
In browser request is the old value

I suspect they're not even the same instance
But `b1` and  `b2` is true

What might be the problem?
Sorry for my English...

```
static FileCache cache1 = new FileCache();
static FileCache cache2 = new FileCache();
public bool Add(string key, byte[] value, TimeSpan timeout = new TimeSpan())
{
    cache1 = this;
    bool b1 = ReferenceEquals(cache1, cache2);
    var response = Find(key);
    string s0 = new string(System.Text.Encoding.UTF8.GetChars(response.Item2));
    using (new ReadLock(_lockEx))
    {
        if (_entriesByKey.TryGetValue(key, out var cacheValue))
        {
            string s1 = new string(System.Text.Encoding.UTF8.GetChars(cacheValue.Value));
        }
    }

    using (new WriteLock(_lockEx))
    {
        string s2 = new string(System.Text.Encoding.UTF8.GetChars(value));
        _entriesByKey[key] = new MemCacheEntry(value, timeout);
        return true;
    }
}

 public (bool, byte[]) Find(string key)
 {
     cache2 = this;
     bool b2 = ReferenceEquals(cache1, cache2);
     using (new ReadLock(_lockEx))
     {
         // Try to find the given key
         if (!_entriesByKey.TryGetValue(key, out var cacheValue))
             return (false, new byte[0]);

         string s3 = new string(System.Text.Encoding.UTF8.GetChars(cacheValue.Value));

         return (true, cacheValue.Value);
     }
 }
```

**Comment by stratdev3** [comment]
Depending what process is updating (writing) your static file, there is a glitch with the underlying FileSystemWatcher not reading correct data. This lead to incorrect cache update.

The bug can be reproduced by using `server.AddStaticContent(www);` and editing some html/js/css files with VisualCode. Then, after writing, NetCoreServer does not see the change.

**Comment by stratdev3** [comment]
Depending the tool (ie: vscode, sublime text...) used to edit a file while server is running, events like `OnChanged()` can be fired multiple times with read or write lock by the underlying saving process.

So `ReadAllBytes()` will at best thrown an exception and sometimes return 0 byte content. Cache will be invalid.

I made a workaround for this based on a on retry (try/catch/sleep/read). Works for 2 yr in production.

**Comment by chronoxor** [comment]
Reproduced! I'll fix this soon
