### ISSUE TITLE
Buffer-size in the 'OnReceived' methods can get too long

### ISSUE THREAD

**Issue by Mufanza** [chronoxor/NetCoreServer#290]
Hi,
First of all, a big thank You to Chronoxor & all the contributors for this amazing library - I've been using it for years and I love it!

Here's one thing that was always perplexing me:
The '_Receive_' and '_OnReceived_' methods of the [TcpSession class](https://github.com/chronoxor/NetCoreServer/blob/master/source/NetCoreServer/TcpSession.cs) have the following signatures:

`(byte[] buffer, long offset, long size)`

However, how can the _offset_ and _size_ parameters be of a **long** type, if the buffer is just a regular array? The maximum length of an array is an **int**, not a **long**! 
So what happens if the methods receive either the '_offset_' or the '_size_' argument with a value larger than Int.MaxValue?
I'd expect one of the following:
Either the method fails with an '_OverflowException_'
Or the extra value will be truncated, resulting in a loss of data.

Is there a real risk of this happening? I wonder if the argument types could be changed from **long** to **int**, or if the method could call itself recursively on a truncated buffer if the size/offset get too big?

**Comment by chronoxor** [comment]
`long offset, long size` was introduced after we migrated our CppServer library to C#, there we use size_t which is 64bit. You should never get values bigger that Int.MaxValue.

**Comment by Mufanza** [comment]
Ah, okay - and thanks for the swift reply!
Would it make sense to change the parameter type from float to int? Or does it break some kind of backwards compatibility?

In any case, if this is known and there's no danger of overflowing the maximum value then I guess there's no issue - so I'm closing this

**Comment by chronoxor** [comment]
Yes mostly for backward compatibility. Maybe in some next major release I'll refactor this.
