### ISSUE TITLE
server send UTF-8 client throw excreption

### ISSUE THREAD

**Issue by devtest2k18** [chronoxor/NetCoreServer#36]
![image](https://user-images.githubusercontent.com/58419118/71401235-ca87d380-265b-11ea-96b4-d1e194b20f24.png)

**Comment by devtest2k18** [comment]
i am use
SendTextAsync("ố");

**Comment by devtest2k18** [comment]
WsSession.cs
![image](https://user-images.githubusercontent.com/58419118/71401436-729d9c80-265c-11ea-9f9a-a4b385a3a99a.png)

**Comment by devtest2k18** [comment]
I replaced
![image](https://user-images.githubusercontent.com/58419118/71401563-d32cd980-265c-11ea-8873-b6c8b4fd704a.png)
it is working

**Comment by devtest2k18** [comment]
method SendText has the same problem

**Comment by devtest2k18** [comment]
SendTextAsync, SendText has the same problem

**Comment by chronoxor** [comment]
Fixed! Thanks a lot!
