### ISSUE TITLE
UDP client send  loop 10000 msg, server throw excreption

### ISSUE THREAD

**Issue by devtest2k18** [chronoxor/NetCoreServer#37]
![image](https://user-images.githubusercontent.com/58419118/71404017-032bab00-2664-11ea-9591-be38cfb46a97.png)

**Comment by chronoxor** [comment]
What is logic of your NetCoreGameServer.UDPEchoServer? It looks like infinite send/receive loop.

**Comment by devtest2k18** [comment]
This is my code
[UDPTest.zip](https://github.com/chronoxor/NetCoreServer/files/3999363/UDPTest.zip)

**Comment by devtest2k18** [comment]
client insert to console: "for mádmfdg fd gdf gdf gdf df sf sd 100000"

**Comment by chronoxor** [comment]
Fixed in 3.0.4. Thank for reporting!
