### ISSUE TITLE
"An asynchronous socket operation is already in progress using this socketasynceventargs instance" Exception

### ISSUE THREAD

**Issue by smhykcll** [chronoxor/NetCoreServer#41]
I get error which i already mentioned in the tittle.This exception throws in TcpSession class in _sendEventArg.SetBuffer() method.My app sends packets periodically.Could u please help me handle this problem?
Thanks

**Comment by wilsonsuryajaya** [comment]
I am also having the same exception either in _sendEventArg.SetBuffer() or _receiveEventArg.SetBuffer(). In my case, it looks like the issue happened during high number of real-time send and receive packets (few hundred bytes-kb packets per second).  Appreciate if you can look into this issue. Thank you
