### ISSUE TITLE
Calling the Buffer.Clear() only resets the offset and size and does not empty the underlying byte array.

### ISSUE THREAD

**Issue by mohammadshahabrafiq** [chronoxor/NetCoreServer#42]
Hello,

I am using the buffer class in my code and I came across some counter intuitive behavior. If I call the clear method I would expect the underlying data to be cleared in addition to the offset and size? Am I missing something? Unit test demonstrating the issue is below. Thanks.

```
[Fact]
public void GivenTheBufferIsClearedThenTheBufferDataShouldBeEmpty()
{
	var buffer = new Buffer(new byte[] { 0x01, 0x02, 0x03 });

	buffer.Clear();

	Assert.Empty(buffer.Data);
}
```

**Comment by chronoxor** [comment]
This is the designed behavior of all session buffers that avoids buffer re-allocations and decrease memory pressure on GC.

**Comment by mohammadshahabrafiq** [comment]
I see. I tried using buffer.Resize(0) but that doesn't work either.

**Comment by chronoxor** [comment]
What is the case you need to clear Buffer in your code? NetCoreServer.Buffer is very specific to be used in sessions/clients. Why don't you choose List<byte> instead?

**Comment by mohammadshahabrafiq** [comment]
Yes I made end up using List. That is something I can easily do. I figured this glass is memory efficient and thought I could take advantage of it. My use case is that I am looking out for messages in the stream the start with STX and end with ETX. If I see an STX and then another STX while waiting for the closing ETX then I clear the buffer.

**Comment by mohammadshahabrafiq** [comment]
@chronoxor I will close this as I can do what I need to do using List?

**Comment by chronoxor** [comment]
Sure, I thinks this issue has nothing to be fixed in NetCoreServer.Buffer

**Comment by mohammadshahabrafiq** [comment]
Cool. Closing.
