### ISSUE TITLE
Connect vs ConnectAsync behavior

### ISSUE THREAD

**Issue by deviousasti** [chronoxor/NetCoreServer#45]
Is there a difference of behavior from `Connect` and `ConnectAsync`?
How to reproduce:

In the Tcp or Ssl Chat Server/Client example change:
```
client.ConnectAsync();
```
to 

```
client.Connect();
```

The client is now unable to receive any data from the server.
The client still connects as expected and is able to send data to the server though.

**Comment by chronoxor** [comment]
`client.Connect()` is synchronous method. If you use sync API you'll need receive data manually using `client.Receive()` method or start receiving loop with `client.ReceiveAsync()` method.

**Comment by deviousasti** [comment]
Thank you. That makes sense. It wasn't very clear to me. 
Was this documented somewhere that I missed?
Should I submit a PR adding this to the method comments?

**Comment by chronoxor** [comment]
I've added some remarks to the Connect() method documentation

**Comment by deviousasti** [comment]
Thank you for all the hard work!
Closing now.
