### ISSUE TITLE
How to limit the maximum connections in TcpServer.

### ISSUE THREAD

**Issue by Mohamed-Abubucker** [chronoxor/NetCoreServer#46]
Hi,

i am using TcpServer in my dotnet core console application and its running in port 5555. memory usage is getting increased frequently.

for example, i tried to run this application for a day and totally 280k messages sent/received (no multicast, only direct messages).

intially, the memory usage was 60 to 70 MB, after a day, it was 1,700MB. i checked my code for memory leakage issues, nothing is strange in my implementation, i am using DI for object initialization and all the unused things were disposed correctly.

still, the memory is getting high. i suspect that its due to number of con-current connections and its keep opened forever. 

i want to force the client to getting disconnected after certain period of time and also want to limit the con-current connections to 500 or 1000.

kindly let me know, how can i implement this?

**Comment by Mohamed-Abubucker** [comment]
Hi,

FYI,

I deployed my tcp server console app into Windows Server 2012 R2 in release mode.

**Comment by Mohamed-Abubucker** [comment]
Hi,
As i investigated further, GC Generation 2 is getting increased and causing memory leakage.

kindly help me to resolve this issue ASAP.

**Comment by Mohamed-Abubucker** [comment]
i am closing this case as no reply from the author regarding this.

**Comment by TailyFair** [comment]
How was this resolved? Forcing GC manually?

**Comment by Mohamed-Abubucker** [comment]
Hi @TailyFair ,

I just implemented automatic process restart trick using cronjobs. for example, every day morning, my cron job will stop the process which consumed lot of memory, and restart the process again. temporarily it solved my memory leakage issue. its just a hack. but no proper solution from the author.
