### ISSUE TITLE
.net Framework 4.8?

### ISSUE THREAD

**Issue by Crushedice** [chronoxor/NetCoreServer#53]
Greetings.
I planned to use the netcoreserver in the current application im working on,
but cannot get it to work as VS cant find the "netstandart" reference.

i saw there was a framework branch already, any chance of getting an update to that one?

**Comment by chronoxor** [comment]
Yes we need to merge master to NetFramework-4.6 branch. Will do this soon.

**Comment by Crushedice** [comment]
Thank you!

**Comment by chronoxor** [comment]
Updated
https://github.com/chronoxor/NetCoreServer/releases/tag/1.9.2
