### ISSUE TITLE
API Proposal: Check Disposed Socket

### ISSUE THREAD

**Issue by erictuvesson** [chronoxor/NetCoreServer#54]
### Justification
It would be nice if there was a way to check if a socket is disposed.
Right now I suppose I can check on `IsConnected` and if connect I expect it is not disposed.

https://github.com/chronoxor/NetCoreServer/blob/master/source/NetCoreServer/TcpSession.cs#L177-L195

### API Proposal

Having a boolean property to just check `IsDisposed` or `IsSocketDisposed` or just a wrapper over socket, just to give a easy to understand property saying that it is disposed.

**Comment by chronoxor** [comment]
Add into release 3.0.8
