### ISSUE TITLE
is it possible to use a fqdn instead of an ip

### ISSUE THREAD

**Issue by ekjuanrejon** [chronoxor/NetCoreServer#67]
I am using the chat client example. I am using a static ip address like 127.0.0.1. I would to use something like tcp.example.com and port 8888.

I am getting an error when using a host name

any ideas?

Thanks

**Comment by chronoxor** [comment]
```
IPHostEntry ipHostInfo = Dns.GetHostEntry(hostName);
IPAddress ipAddress = ipHostInfo.AddressList.FirstOrDefault(a => a.AddressFamily == AddressFamily.InterNetwork);
```
