### ISSUE TITLE
WebsocketServer Connection Upgrade

### ISSUE THREAD

**Issue by marco-vogt** [chronoxor/NetCoreServer#71]
Hey,

i'm having difficulties connecting to my NetCoreServer-Websocketserver from some clients. I found out that some Websocket libraries (for example boost beast) are sending "Connection: upgrade" in the handshake and the NetCoreServer Websocketserver is expecting an uppercase "Upgrade" -> "Connection: Upgrade". The handshake in this scenario is not possible.

Is it possible these string comparisons could be made case invariant? If yes, i can send a PR.

Cheers

**Comment by chronoxor** [comment]
Thanks for reporting! Fixed in 3.0.18
