### ISSUE TITLE
Windows multithreading performance (scheduler)

### ISSUE THREAD

**Issue by JohannesDeml** [chronoxor/NetCoreServer#80]
I did a performance test on an old linux machine and on a new windows machine, and was quite surprised to see, that the old linux computer performed better. Before I start to dig depper on why that is, I wanted to ask if that behavior is already known.

Here a breakdown on the tests and results:

### Linux
* OS: Ubuntu 20.04.1 LTS
* CPU: Intel® Core™ i5-3570K CPU @ **3.40GHz × 4**
* Mainboard:  Gigabyte Z77X-D3H **Gb LAN (Atheros)**
* RAM: G.Skill 16GB (2 x 8 GB) DDR3-1600 (Part number: F3-1600C11-8GNT)

### Windows
* OS: Windows 10 Pro 2004 x64 (v10.0.19041)
* CPU: AMD Ryzen 7 3700X **3.6 GHz 8-Core**
* Mainboard: MSI MAG X570 TOMAHAWK WIFI ATX AM4 **Lan: 2.5 Gbit/s**
* RAM: G.Skill Aegis 32 GB (2 x 16 GB) DDR4-3200 CL16
[Complete Build](https://pcpartpicker.com/b/8MMcCJ)

## Test
* `UdpEchoClient -c 100`
* Both built as release builds with .Net Core 3.1.8

### Linux
```
Server address: 127.0.0.1
Server port: 3333
Working clients: 100
Working messages: 1000
Message size: 32
Seconds to benchmarking: 10

Clients connecting...Done!
Benchmarking...Done!
Clients disconnecting...Done!
All clients disconnected!

Errors: 0

Total time: 11.042 s
Total data: 35.794 MiB
Total messages: 1172304
Data throughput: 3.245 MiB/s
Message latency: 9.419 mcs
Message throughput: 106166 msg/s
```
![image](https://user-images.githubusercontent.com/4518980/94121854-2208d900-fe52-11ea-93cb-b88f2a4ed770.png)

### Windows
```
Server address: 127.0.0.1
Server port: 3333
Working clients: 100
Working messages: 1000
Message size: 32
Seconds to benchmarking: 10

Clients connecting...Done!
Benchmarking...Done!
Clients disconnecting...Done!
All clients disconnected!

Errors: 0

Total time: 10.529 s
Total data: 24.896 MiB
Total messages: 815111
Data throughput: 2.371 MiB/s
Message latency: 12.918 mcs
Message throughput: 77409 msg/s
```
![NVIDIA_Share_Q5CCpmU1zV](https://user-images.githubusercontent.com/4518980/94121800-0f8e9f80-fe52-11ea-8c8c-d496cb5caade.png)

As you can see, only some cores of the threadripper on the windows machine put their energy in running the benchmark. But even with those cores running I would have expected better results on windows (at least compared to my 9 year old build that runs ubuntu).

Any idea how I can make sense of those results?

**Comment by JohannesDeml** [comment]
Okay, so I did another test with a ubuntu usb live system on the newer machine, here are the results:

### Ubuntu on new machine

```
Server address: 127.0.0.1
Server port: 3333
Working clients: 1
Working messages: 1000
Message size: 32
Seconds to benchmarking: 10

Clients connecting...Done!
Benchmarking...Done!
Clients disconnecting...Done!
All clients disconnected!

Errors: 0

Total time: 10.013 s
Total data: 46.141 MiB
Total messages: 1511854
Data throughput: 4.622 MiB/s
Message latency: 6.623 mcs
Message throughput: 150980 msg/s
```
![grafik](https://user-images.githubusercontent.com/4518980/94250783-f6552400-ff21-11ea-8a4b-99f154cef588.png)

Seems like performance is 2x better than on windows. Not sure if that number would be even higher when I would have installed ubuntu instead of running it on an old usb stick. Apparently the problem is the windows scheduler for threads that doesn't make the best choices when it has a lot of threads available.

@chronoxor Should I keep the issue open for either documentation or a potential optimiation for handling windows threads?

**Comment by chronoxor** [comment]
NetCoreServer relays on .net core networking. Under the hood on windows it use IO completion ports Windows API. Currently I don't see any optimization ways particular in NetCoreServer library on Windows.

**Comment by JohannesDeml** [comment]
> 
> 
> NetCoreServer relays on .net core networking. Under the hood on windows it use IO completion ports Windows API. Currently I don't see any optimization ways particular in NetCoreServer library on Windows.

Okay, I already thought so. Still, very interesting to have 2x better performance on ubuntu, I didn't expect that!

**Comment by sgf** [comment]
when u test,did u let the client run on same machine and same OS.
and when use .net core do u open the ServerGC Mode.

then u will got the result of the server performance.

**Comment by JohannesDeml** [comment]
> 
> 
> when u test,did u let the client run on same machine and same OS.
> and when use .net core do u open the ServerGC Mode.
> 
> then u will got the result of the server performance.
> 
> In addition, I have always heard that the performance of Windows' UDP implementation is poor, and the .net's UDP implementation is even worse. Microsoft does not attach importance to the UDP protocol.
> so,maybe as you result is right.

Sorry for the late response, I've taken some time off from the digital world.
Yes, my test setup was in both cases on one machine.

I just ran the performance test as is, which is not using ServerGC Mode.
I added 
```
<PropertyGroup>
  <ServerGarbageCollection>true</ServerGarbageCollection>
</PropertyGroup>
```
to both UdpEchoServer.csproj and UdpEchoClient.csproj and did a clean build.
The results are pretty much the same as before (slight variation occurs, but also happened before).

**Comment by sgf** [comment]
> > when u test,did u let the client run on same machine and same OS.
> > and when use .net core do u open the ServerGC Mode.
> > then u will got the result of the server performance.
> > In addition, I have always heard that the performance of Windows' UDP implementation is poor, and the .net's UDP implementation is even worse. Microsoft does not attach importance to the UDP protocol.
> > so,maybe as you result is right.
> 
> Sorry for the late response, I've taken some time off from the digital world.
> Yes, my test setup was in both cases on one machine.
> 
> I just ran the performance test as is, which is not using ServerGC Mode.
> I added
> 
> ```
> <PropertyGroup>
>   <ServerGarbageCollection>true</ServerGarbageCollection>
> </PropertyGroup>
> ```
> 
> to both UdpEchoServer.csproj and UdpEchoClient.csproj and did a clean build.
> The results are pretty much the same as before (slight variation occurs, but also happened before).

Anyway, your test is very valuable. Thanks for sharing

**Comment by JohannesDeml** [comment]
> 
> 
> > to both UdpEchoServer.csproj and UdpEchoClient.csproj and did a clean build.
> > The results are pretty much the same as before (slight variation occurs, but also happened before).
> 
> on new ver Windows,there has a New Tech name **Registered I/O Networking Extensions (RIO)**,its good for using on UDP.
> 
> Any Way,Your test is very valuable. Thanks for sharing

Interesting, haven't heared of RIO before, but it seems to not be integrated into .Net core and that you would need to write some native code, that is then connected to your managed code ([Source](https://stackoverflow.com/questions/18419117/rio-registered-i-o-sockets-in-net)).

Still interesting to know, even though I don't think it is interesting for this repo.
