### ISSUE TITLE
Websocket SendAsync Disconnects client immediately

### ISSUE THREAD

**Issue by Rustypredator** [chronoxor/NetCoreServer#88]
So, i'm having the issue that using SendAsnyc() on the Session immediately closes the Session and Disconnects the client.

My Code on the Server:
```csharp
public void sendSingle(System.Guid guid, string line) {
    SslSession target = ((WssServer)Server).FindSession(guid);
    try {
        target?.SendAsync(line); //this disconnects clients...
        Console.WriteLine("Sent " + line + " to " + guid.ToString());
    } catch (Exception e) {
        Console.WriteLine(e);
    }
}
```
everything gets executed and the Server does'nt throw any errors.
but the client immediately disconnects when the server sends the line.
I tried multiple clients, javascript, lua etc.
If im doing something stupid here, please point it out, i havent used c# for a while...

**Comment by summrey** [comment]
I have same problem , @Rustypredator Have you finally found a solution？

**Comment by Dmitriy147** [comment]
+1...

**Comment by chronoxor** [comment]
SendAsync() is not a way to send user data into WebSocket! It's a low level SSL send method. WebSocket needs to have prepared frame before raw send.

Please try to use SendText()/SendBinary() methods which prepare WebSocket frame and then send raw data using SendAsync():
```
        public long SendText(string text)
        {
            lock (WebSocket.WsSendLock)
            {
                var data = Encoding.UTF8.GetBytes(text);
                WebSocket.PrepareSendFrame(WebSocket.WS_FIN | WebSocket.WS_TEXT, false, data, 0, data.Length);
                return base.Send(WebSocket.WsSendBuffer.ToArray());
            }
        }
```

**Comment by Dmitriy147** [comment]
Thanks for your answer, but any way my client disconnects evry time , but some seconds later after request..My client based on Fleck package and broadcast is working fine. Could you please show the full code from example of WsChatServer?

**Comment by chronoxor** [comment]
https://github.com/chronoxor/NetCoreServer/blob/master/examples/WsChatServer/Program.cs

**Comment by Dmitriy147** [comment]
Thanks a lot! All working fine!
 It is need to use: SendTextAsync(message);
instead of: SendAsync(message);

**Comment by chronoxor** [comment]
Yes, Send()/SendAsync() is a socket low level method inherited from TcpSocket/SslSocket. For WebSocket please use SendBinaryAsync()/SendTextAsync()/SendPingAsync()/SendPongAsync() methods from WsSession/WssSession.
