### ISSUE TITLE
UDPserver require 2 functions

### ISSUE THREAD

**Issue by koujiangheng** [chronoxor/NetCoreServer#96]
In TcpSession there are 2 functions 

- protected virtual void OnReceived(string message) { }

- protected virtual void OnReceived(byte[] buffer){ }

however in UdpSession these virtual functions do not exist.

- In addition, can you make a udpsession? which saves EndPoint and etc. it is convient for programmer to use session rather than use EndPoint.
something like:

 public static ConcurrentDictionary<EndPoint, UDPSessionBase> Sessions
            = new ConcurrentDictionary<EndPoint, UDPSessionBase>();

protected override void OnReceived(EndPoint endPoint, byte[] buffer, long offset, long size)
        {
            UdpSession session;
            if (!Sessions.TryGetValue(endPoint, out session))
            {
                session = CreateSession(endPoint);
                Sessions.TryAdd(endPoint, session);
            }
            OnReceived(session, buffer,offset,size);
}

**Comment by chronoxor** [comment]
UDP protocol is sessoin less. On server/client you just receive datagrams as binary array from the given UDP endpoint. You can handle this datagram in `OnReceived(EndPoint endpoint, byte[] buffer, long offset, long size)` and send back the response with `Send(EndPoint endpoint, byte[] buffer)`

**Comment by koujiangheng** [comment]
> UDP protocol is sessoin less. On server/client you just receive datagrams as binary array from the given UDP endpoint. You can handle this datagram in `OnReceived(EndPoint endpoint, byte[] buffer, long offset, long size)` and send back the response with `Send(EndPoint endpoint, byte[] buffer)`

UDP indeed session less, however we need sometimes store the endpoint to our client pool for convient use. In our UniSpy case there are many servers report data to our udp server, we need to store the data and the endpoint for later use.

**Comment by chronoxor** [comment]
From my point of view it is not a UDP essentials functionality. I think you can implement all this logic in upper level in your code.

**Comment by koujiangheng** [comment]
> From my point of view it is not a UDP essentials functionality. I think you can implement all this logic in upper level in your code.

Make sence, haha. Have a nice day
