### ISSUE TITLE
"An asynchronous socket operation is already in progress using this socketasynceventargs instance" Exception

### ISSUE THREAD

**Issue by CSA** [chronoxor/NetCoreServer#99]
I get this exception when i run TcpEchoClient project in performance folder.
This exception is not reproduced every time, it will reproduced after run about 5 times.
This exception throws in TcpClient class in TrySend method, could u help me to solve this problem?
<img width="523" alt="img" src="https://user-images.githubusercontent.com/12838089/100418314-88fa7680-30bd-11eb-9e8b-f3601680930f.png">
Thanks

**Comment by chronoxor** [comment]
Thanks for reporting. I'll check the issue.

**Comment by chronoxor** [comment]
Please check the version 5.0.2 - https://github.com/chronoxor/NetCoreServer/releases/tag/5.0.2

**Comment by CSA** [comment]
I tested this issue in new version, it has been fixed, Thanks :)
